# Generated by Django 5.0.1 on 2024-01-16 19:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 16, 19, 51, 55, 156366, tzinfo=datetime.timezone.utc), verbose_name='Fecha de publicación'),
        ),
    ]
